FROM node:20-alpine as development

WORKDIR /usr/src/app

# Instalar dependencias necesarias (si hubiera nativas)
# RUN apk add --no-cache python3 make g++

COPY package*.json ./

RUN npm install

# El código se monta vía volúmenes en dev

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
