# Etapa de construcción
FROM node:20-alpine AS builder

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Etapa de producción
FROM node:20-alpine

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/package*.json ./
RUN npm install --only=production

COPY --from=builder /usr/src/app/dist ./dist

# EXPOSE depende de tu puerto en production, por defecto Nest usa 8001 en tu config
EXPOSE 8001

CMD ["node", "dist/main"]
